name: Release UMD Bundle

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js (you can modify the version if necessary)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the version you need

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the UMD bundle (modify your build command here)
      - name: Build UMD bundle
        run: npm run lib:umd # or whatever your build script is

      # Create GitHub Release and upload assets
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          body: |
            Release of version ${{ github.ref }}.
            This release includes the UMD bundle and other assets.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically available in GitHub Actions

      # Upload the UMD bundles to the GitHub release
      - name: Upload UMD bundles
        uses: actions/upload-artifact@v2
        with:
          name: umd-bundles
          path: umd
